<img src="https://github.com/StevenMena/01MIAR_Python_IA/blob/main/img/viu_logo.png?raw=1" width="200">

## 01MIAR - Actividad Final
##Nombres: Steven Mena

### Introducción

Python es uno de los lenguajes de programación de referencia en el ámbito del tratamiento y análisis de datos. Existen diferentes funciones internas de Python y librerías que permiten mejorar la eficiencia de estos trabajos como es el caso de NumPy para el cálculo numérico y Pandas para operaciones con datos estructurados. Junto con estas operaciones, la visualización es un proceso importante para comprender mejor los datos. Con Matplotlib combinado con Pandas, y en el entorno Jupyter, es posible desarrollar y explicar el proceso de tratamiento y análisis de datos con gran facilidad.

### Objetivo

- Aplicar diferentes técnicas de tratamiento de datos explicadas durante el curso
- Explorar datos y evaluarlos mediante el uso de Pandas
- Aplicar adecuadamente técnicas de visualización
- Desarrollar una capacidad crítica y conocer fuentes de información

##El dataset escogido es sobre las distintas aplicaciones moviles que existen para  Apple
#Fuente: https://www.kaggle.com/datasets/ramamet4/app-store-apple-data-set-10k-apps

#Importar librerías

In [2]:
#Dos líbrerias fundamentales en python para el manejo de datos
import numpy as np 
import pandas as pd 

import matplotlib as plt #Librería para plotear o gráficar
import os #Líbreria para manipulación de archivos 
import seaborn as sns #Líbreria que no sirve para crear gráficos o plotear dinámicamente

##Cargar dataset
El dataset es un archivo en formato csv.
Para cargar el dataset lo podemos hacer con la librería os o directamente con pandas con su función read_csv.
Para este trabajo se van ocupar dos dataset, que se relacionan por medio del id de la aplicación movil.

In [5]:
#Si nuestro archivo esta en la misma ubicación que este notebook, no necesitamos especificar su folder o la ruta
ruta_dataset = os.path.join('AppleStore.csv')
#Especificamos la ruta del archivo, su carácter como separación, el motor y si posse index propio
#Se almancena el csv en un objeto dataframe de panda
apple_mobile_apps = pd.read_csv(ruta_dataset, sep=',', index_col=0, engine='python')


#Cargando el segundo dataset
#Esta vez demostramos que se puede cargar un dataset en formato csv directamente con la libería pandas
apple_mobile_apps_desc = pd.read_csv('appleStore_description.csv', sep=',', index_col=0, engine='python')

##Visualización de un dataset

In [8]:
#función para mostrar todos los datos del dataset
display(apple_mobile_apps)

display(apple_mobile_apps_desc)

,id,track_name,size_bytes,currency,price,rating_count_tot,rating_count_ver,user_rating,user_rating_ver,ver,cont_rating,prime_genre,sup_devices.num,ipadSc_urls.num,lang.num,vpp_lic
1,281656475,PAC-MAN Premium,100788224,USD,3.99,21292,26,4.0,4.5,6.3.5,4+,Games,38,5,10,1
2,281796108,Evernote - stay organized,158578688,USD,0.00,161065,26,4.0,3.5,8.2.2,4+,Productivity,37,5,23,1
3,281940292,"WeatherBug - Local Weather, Radar, Maps, Alerts",100524032,USD,0.00,188583,2822,3.5,4.5,5.0.0,4+,Weather,37,5,3,1
4,282614216,"eBay: Best App to Buy, Sell, Save! Online Shop...",128512000,USD,0.00,262241,649,4.0,4.5,5.10.0,12+,Shopping,37,5,9,1
5,282935706,Bible,92774400,USD,0.00,985920,5320,4.5,5.0,7.5.1,4+,Reference,37,5,45,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11081,1187617475,Kubik,126644224,USD,0.00,142,75,4.5,4.5,1.3,4+,Games,38,5,1,1
11082,1187682390,VR Roller-Coaster,120760320,USD,0.00,30,30,4.5,4.5,0.9,4+,Games,38,0,1,1
11087,1187779532,Bret Michaels Emojis + Lyric Keyboard,111322112,USD,1.99,15,0,4.5,0.0,1.0.2,9+,Utilities,37,1,1,1
11089,1187838770,VR Roller Coaster World - Virtual Reality,97235968,USD,0.00,85,32,4.5,4.5,1.0.15,12+,Games,38,0,2,1
11097,1188375727,Escape the Sweet Shop Series,90898432,USD,0.00,3,3,5.0,5.0,1.0,4+,Games,40,0,2,1

,track_name,size_bytes,app_desc
id,,,
281656475,PAC-MAN Premium,100788224,"SAVE 20%, now only $3.99 for a limited time!\n..."
281796108,Evernote - stay organized,158578688,Let Evernote change the way you organize your ...
281940292,"WeatherBug - Local Weather, Radar, Maps, Alerts",100524032,Download the most popular free weather app pow...
282614216,"eBay: Best App to Buy, Sell, Save! Online Shop...",128512000,The eBay app is the best way to find anything ...
282935706,Bible,92774400,On more than 250 million devices around the wo...
...,...,...,...
1187617475,Kubik,126644224,Place the falling blocks correctly in order to...
1187682390,VR Roller-Coaster,120760320,A thrilling virtual reality roller coaster exp...
1187779532,Bret Michaels Emojis + Lyric Keyboard,111322112,"Rock star Bret Michaels, winner of Celebrity A..."
1187838770,VR Roller Coaster World - Virtual Reality,97235968,VR Roller Coaster World is an app for Google C...
1188375727,Escape the Sweet Shop Series,90898432,5 previous escape games plus 1 new game in one...

In [ ]:
#Visualizar solo 10 filas de un dataset
display(apple_mobile_apps.sample(10))

#Visualizar solo los primeros elementos de un dataset
display(apple_mobile_apps.head(5))

#Visualizar solo los últimos elementos de un dataset
display(apple_mobile_apps.tail(1))

##Datos generales de un dataset

In [10]:
# Muestra los tipos de datos de cada columna
apple_mobile_apps.dtypes

id                    int64
track_name           object
size_bytes            int64
currency             object
price               float64
rating_count_tot      int64
rating_count_ver      int64
user_rating         float64
user_rating_ver     float64
ver                  object
cont_rating          object
prime_genre          object
sup_devices.num       int64
ipadSc_urls.num       int64
lang.num              int64
vpp_lic               int64
dtype: object

In [11]:
# Muestra información estadistica sobre cada columna del dataset
display(apple_mobile_apps.describe())

,id,size_bytes,price,rating_count_tot,rating_count_ver,user_rating,user_rating_ver,sup_devices.num,ipadSc_urls.num,lang.num,vpp_lic
count,7.197000e+03,7.197000e+03,7197.000000,7.197000e+03,7197.000000,7197.000000,7197.000000,7197.000000,7197.000000,7197.000000,7197.000000
mean,8.631310e+08,1.991345e+08,1.726218,1.289291e+04,460.373906,3.526956,3.253578,37.361817,3.707100,5.434903,0.993053
std,2.712368e+08,3.592069e+08,5.833006,7.573941e+04,3920.455183,1.517948,1.809363,3.737715,1.986005,7.919593,0.083066
min,2.816565e+08,5.898240e+05,0.000000,0.000000e+00,0.000000,0.000000,0.000000,9.000000,0.000000,0.000000,0.000000
25%,6.000937e+08,4.692275e+07,0.000000,2.800000e+01,1.000000,3.500000,2.500000,37.000000,3.000000,1.000000,1.000000
50%,9.781482e+08,9.715302e+07,0.000000,3.000000e+02,23.000000,4.000000,4.000000,37.000000,5.000000,1.000000,1.000000
75%,1.082310e+09,1.819249e+08,1.990000,2.793000e+03,140.000000,4.500000,4.500000,38.000000,5.000000,8.000000,1.000000
max,1.188376e+09,4.025970e+09,299.990000,2.974676e+06,177050.000000,5.000000,5.000000,47.000000,5.000000,75.000000,1.000000

In [13]:
#Info general del dataset
apple_mobile_apps.info()

#Dimensiones del dataset
apple_mobile_apps.shape

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7197 entries, 1 to 11097
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id                7197 non-null   int64
 1   track_name        7197 non-null   object
 2   size_bytes        7197 non-null   int64
 3   currency          7197 non-null   object
 4   price             7197 non-null   float64
 5   rating_count_tot  7197 non-null   int64
 6   rating_count_ver  7197 non-null   int64
 7   user_rating       7197 non-null   float64
 8   user_rating_ver   7197 non-null   float64
 9   ver               7197 non-null   object
 10  cont_rating       7197 non-null   object
 11  prime_genre       7197 non-null   object
 12  sup_devices.num   7197 non-null   int64
 13  ipadSc_urls.num   7197 non-null   int64
 14  lang.num          7197 non-null   int64
 15  vpp_lic           7197 non-null   int64
dtypes: float64(3), int64(8), object(5)
memory usage: 955.9+ KB

(7197, 16)

##Acceso a datos

In [14]:
#Acceder a una columna por su nombre
display(apple_mobile_apps['track_name'])

1                                          PAC-MAN Premium
2                                Evernote - stay organized
3          WeatherBug - Local Weather, Radar, Maps, Alerts
4        eBay: Best App to Buy, Sell, Save! Online Shop...
5                                                    Bible
                               ...
11081                                                Kubik
11082                                    VR Roller-Coaster
11087                Bret Michaels Emojis + Lyric Keyboard
11089            VR Roller Coaster World - Virtual Reality
11097                         Escape the Sweet Shop Series
Name: track_name, Length: 7197, dtype: object

In [16]:
#Acceder a un dato de una columna en especifica
display(apple_mobile_apps['track_name'][1])

'PAC-MAN Premium'

##Limpieza de datos del dataset